on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: docker login https://ghcr.io -u token -p ${{ secrets.GHCR_PAT }}

      - run: docker pull alpine

      - run: docker tag alpine ghcr.io/${{ github.repository }}   

      - run: docker push ghcr.io/${{ github.repository }}
